erecruitment/config/routes.rb
Erecruitment::Application.routes.draw do

  resources :answers

  get "testpaper/test"
  get "candidates/index"
  get "candidates/show_tests"
  get "candidates/show_results"
  get "candidate/index"
  get "organization/index"
  resources :tests

  get 'admin' => 'admin#index'
 
controller :sessions do
 get 'login' => :new
 post 'login' => :create
 delete 'logout' => :destroy
end
  
  resources :users

  get "testpaper/index"

  resources :my_questions

end

erecruitment/app/models/user.rb
class User < ActiveRecord::Base
USER_ROLE=[ "Candidate", "Organisation" ]
attr_accessible :name, :email_id, :date_of_birth, :address, :role, :qualification, :password, :password_confirmation

validates :name,
	:presence => TRUE,
	:length => {
		:minimum => 2,
		:allow_blank => TRUE
	}
validates :role,
	:presence => TRUE


validates :password,
	:presence => TRUE,
	:length => {
		:minimum => 6,
		:allow_blank => TRUE
	},
	:confirmation => TRUE

validates :password_confirmation,
	:presence => TRUE

validates :email_id, 
	:presence => true, 
	:uniqueness=> true
end

erecruitment/app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users
  # GET /users.json
  def index

    @users = User.all
                           
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
  end
end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
  end
end

  # GET /users/new
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
  end
end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        Notification.registration(@user).deliver
        format.html { redirect_to login_url,
 notice: 'User #{@user.name} was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_url,
 notice: 'User #{@user.name} was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  def view
  render :layout => false
end
end

erecruitment/app/helpers/users_helper.rb
module UsersHelper
end

erecruitment/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :role %><br>
    <%= f.select :role, User::USER_ROLE,
        prompt: 'Select User type/role' %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, size: 40 %>
  </div>
  <div class="field">
    <%= f.label :email_id %><br>
    <%= f.email_field :email_id, size: 40 %>
  </div>
  <div class="field">
    <%= f.label :password, 'Password' %><br>
    <%= f.password_field :password, size: 40 %>
  </div>
  <div>
    <%= f.label :password_confirmation, 'Confirm' %><br />
    <%= f.password_field :password_confirmation, size: 40 %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br>
    <%= f.text_field :date_of_birth %>
  </div>
  <div class="field">
    <%= f.label :qualification %><br>
    <%= f.text_field :qualification %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address, row: 3,cols: 40 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

erecruitment/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

erecruitment/app/views/users/index.html.erb
<h1>Listing users</h1>
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Role</th>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Date of birth</th>
      <th>Qualification</th>
      <th>Address</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.role %></td>
        <td><%= user.name %></td>
        <td><%= user.email_id %></td>
        <td><%= user.password %></td>
        <td><%= user.date_of_birth %></td>
        <td><%= user.qualification %></td>
        <td><%= user.address %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= button_to 'Destroy', user, :method => :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p>
<br>

<%= link_to 'New User', new_user_path %>

erecruitment/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', login_path %>

erecruitment/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email_id %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @user.date_of_birth %>
</p>

<p>
  <strong>Qualification:</strong>
  <%= @user.qualification %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>