erecruitment/config/routes.rb
Erecruitment::Application.routes.draw do

  resources :answers

  get "testpaper/test"
  get "candidates/index"
  get "candidates/show_tests"
  get "candidates/show_results"
  get "candidate/index"
  get "organization/index"
  resources :tests

  get 'admin' => 'admin#index'
 
controller :sessions do
 get 'login' => :new
 post 'login' => :create
 delete 'logout' => :destroy
end
  
  resources :users

  get "testpaper/index"

  resources :my_questions

end

erecruitment/app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
	layout "candidatelayout"
  def index
  end

  def show_tests
  	sql="select set_by, number_of_questions, duration, cutoff from tests where id NOT IN (select distinct test_id from answers where user_id="+session[:user_id].to_s+")"
  	@tests=Test.find_by_sql(sql)
  end

  def show_results
  	sql="select r.marks, t.set_by, t.number_of_questions, r.pass_or_fail  from test_results r join tests t where r.test_id=t.id AND r.user_id="+session[:user_id].to_s
  	@results=TestResult.find_by_sql(sql)
  end

end

erecruitment/app/helpers/candidates_helper.rb
module CandidatesHelper
end

erecruitment/app/views/candidates/index.html.erb
<h1> Welcome!!! </h1>


<h3> This Online Demo Test is intended, to give experience of the navigation, look and feel of the online test to the applicants. Click Below link to give Demo Test. </h3>
<h3>
<%= link_to 'Give Demo Test', testpaper_index_url(:test_owner => "admin"), 
   :class =>'mylink' %>
</h3>

</br></br>
<h3> According to your Submitted Profile, Following test are alloted to you.</br>
  To check avilable Tests,Click the link Below. </h3>
<h3>

<h3>
 <%= link_to 'Check Available Tests', candidates_show_tests_path , :class =>'mylink' %>
</h3>

</br></br>
<h3>
	<%= link_to 'Check Test Results', candidates_show_results_path %>
</h3>

erecruitment/app/views/candidates/show_results.html.erb
<h1>Test Results</h1>

 <% @results.each do |result| %>

 <h2><%= result.set_by %></h2>

 <% if result.pass_or_fail=="pass" %>
 <% remark="Congratulations!! You have passed the test.." %>
 <% else %>
 <% remark="Sorry.. you failed" %>
 <% end %>
<table border=1>
	
		<tr>
			<th>Total No. of questions</th>
			<th>Marks Obtained</th>
			<th>Remark</th>
			<th>Next stage</th>
		</tr>
	
	<tr>
		<td><%= result.number_of_questions.to_s %></td>
		<td><%= result.marks.to_s %></td>
		<td><%= remark %></td>
		<td><% if result.pass_or_fail=="pass" %>
			<%= link_to 'Start Interview', candidates_show_results_path %>
			<% else %>
			----
			<% end %>
		</td>
	</tr>
</table>

<% end %>

erecruitment/app/views/candidates/show_test.html.erb
<h1>Availlable tests</h1>

<table>
  <thead>
    <tr>
      <th>Test Name</th>
      <th>No. of Questions</th>
      <th>Duration</th>
      <th>Cutoff</th>
      <th></th>

    </tr>
  </thead>

  <tbody>
    <% @tests.each do |test| %>
      <tr>
        <% t_name=test.set_by %>
        <% t_name=t_name.upcase+" Aptitude Test" %>
        <td><%= t_name %></td>
        <td><%= test.number_of_questions %></td>
        <td><%= test.duration+" mins" %></td>
        <td><%= test.cutoff %></td>
        <td><%= link_to 'Start Test', testpaper_url %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>
<div>
  <%= button_to 'Logout', logout_path, :method =>"delete" %>
</div>
<br>



erecruitment/app/views/candidates/show_tests.html.erb
<h1>Availlable tests</h1>

<table>
  <thead>
    <tr>
      <th>Test Name</th>
      <th>No. of Questions</th>
      <th>Duration</th>
      <th>Cutoff</th>
      <th></th>

    </tr>
  </thead>

  <tbody>
    <% @tests.each do |test| %>
      <tr>
        <% t_name=test.set_by %>
        <% t_name=t_name.upcase+" Aptitude Test" %>
        <td><%= t_name %></td>
        <td><%= test.number_of_questions %></td>
        <td><%= test.duration.to_s+" mins" %></td>
        <td><%= test.cutoff %></td>
        <td><%= link_to 'Start Test', testpaper_test_url(:test_id => test.id , :question_id => -1) %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>
<div>
  <%= button_to 'Logout', logout_path, :method =>"delete" %>
</div>

<br>