erecruitment/config/routes.rb
Erecruitment::Application.routes.draw do

  resources :answers

  get "testpaper/test"
  get "candidates/index"
  get "candidates/show_tests"
  get "candidates/show_results"
  get "candidate/index"
  get "organization/index"
  resources :tests

  get 'admin' => 'admin#index'
 
controller :sessions do
 get 'login' => :new
 post 'login' => :create
 delete 'logout' => :destroy
end
  
  resources :users

  get "testpaper/index"

  resources :my_questions

end

erecruitment/app/models/my_question.rb
class My_question < ActiveRecord::Base
	 attr_accessible :anwser, :option_a, :option_b, :option_c, :option_d, :question, :difficulty_level, :created_by, :question_type

	 validates :question, :option_a, :option_b, :option_c, :option_d, :anwser, :created_by, :question_type, :difficulty_level, presence: true,allow_blank: true
     validates :question, uniqueness: true
     validates :difficulty_level, numericality: {greater_than_or_equal_to: 1}
end

erecruitment/app/controllers/my_questions_controller.rb
class MyQuestionsController < ApplicationController
  #before_action :set_my_question, only: [:show, :edit, :update, :destroy]

  def index
    @my_questions = My_question.paginate(:page => params[:page], :per_page => 7)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @my_questions }
    end
  end

  # GET /my_questions/1
  # GET /my_questions/1.json
  def show
    @my_question = My_question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @my_question }
    end
  end

  # GET /my_questions/new
  # GET /my_questions/new.json
  def new
    @my_question = My_question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @my_question }
    end
  end

  # GET /my_questions/1/edit
  def edit
    @my_question = My_question.find(params[:id])
  end

  # POST /my_questions
  # POST /my_questions.json
  def create
    @my_question = My_question.new(params[:my_question])

    respond_to do |format|
      if @my_question.save
        format.html { redirect_to @my_question, notice: 'my_question was successfully created.' }
        format.json { render json: @my_question, status: :created, location: @my_question }
      else
        format.html { render action: "new" }
        format.json { render json: @my_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /my_questions/1
  # PUT /my_questions/1.json
  def update
    @my_question = My_question.find(params[:id])

    respond_to do |format|
      if @my_question.update_attributes(params[:my_question])
        format.html { redirect_to @my_question, notice: 'my_question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @my_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_questions/1
  # DELETE /my_questions/1.json
  def destroy
    @my_question = My_question.find(params[:id])
    @my_question.destroy

    respond_to do |format|
      format.html { redirect_to my_questions_url }
      format.json { head :no_content }
    end
  end
end

erecruitment/app/helpers/my_questions_helper.rb
module MyQuestionsHelper
	
end

erecruitment/app/views/my_questions/_form.html.erb
<%= form_for(@my_question) do |f| %>
  <% if @my_question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@my_question.errors.count, "error") %> prohibited this my_question from being saved:</h2>

      <ul>
      <% @my_question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_area :question %>
  </div>
  <div class="field">
    <%= f.label :option_a %><br>
    <%= f.text_field :option_a %>
  </div>
  <div class="field">
    <%= f.label :option_b %><br>
    <%= f.text_field :option_b %>
  </div>
  <div class="field">
    <%= f.label :option_c %><br>
    <%= f.text_field :option_c %>
  </div>
  <div class="field">
    <%= f.label :option_d %><br>
    <%= f.text_field :option_d %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_field :anwser %>
  </div>
  <div class="field">
    <%= f.label :question_type %><br>
    <%= f.text_field :question_type %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br>
    <%= f.text_field :created_by %>
  </div>
  <div class="field">
    <%= f.label :difficulty_level %><br>
    <%= f.number_field :difficulty_level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

erecruitment/app/views/my_questions/edit.html.erb
<h1>Editing my_question</h1>

<%= render 'form' %>

<%= link_to 'Show', @my_question %> |
<%= link_to 'Back', my_questions_path %>

erecruitment/app/views/my_questions/index.html.erb
<h2>Listing Questions </h2>

<%= will_paginate @posts %>
</br>
    <% @my_questions.each do |my_question| %>
        <div class="entry">
          <h2><b>Question: <%= my_question.question %></b></h2></br>
           <div class="option">
            <span class="answer">
              <b>Option a: <%= my_question.option_a %></b></br>
              <b>Option b: <%= my_question.option_b %></b></br>
              <b>Option c: <%= my_question.option_c %></b></br>
              <b>Option d: <%= my_question.option_d %></b></br>
              <b>Anwser: <%= my_question.anwser %></b><br>
              <b>Question type: <%= my_question.question_type %></b></br>
              <b>Created by: <%= my_question.created_by %></b></br>
              <b>Difficulty level:<%= my_question.difficulty_level %></b></br></br>
              <%= button_to 'Show', my_question, :method =>"get" , :class=> 'button' ,   :id=> 'button' %>
              <%= button_to 'Edit', edit_my_question_path(my_question), :method =>"get" , :class=> 'button' ,   :id=> 'button' %>
              <%= button_to 'Destroy', my_question, method: :delete, data: { confirm: 'Are you sure?' } , :class=> 'button' ,   :id=> 'button' %>
            </span>
          </div>
          </div>
      </br></br>
      
    <% end %>
  <%= link_to 'New Question', new_my_question_path , :class=> 'mylink' , :id=> 'mylink'%>

</br>
<%= will_paginate @posts %>

erecruitment/app/views/my_questions/new.html.erb
<h1>New my_question</h1>

<%= render 'form' %>
<%= #link_to 'Back', my_questions_path %>

erecruitment/app/views/my_questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @my_question.question %>
</p>

<p>
  <strong>Option a:</strong>
  <%= @my_question.option_a %>
</p>

<p>
  <strong>Option b:</strong>
  <%= @my_question.option_b %>
</p>

<p>
  <strong>Option c:</strong>
  <%= @my_question.option_c %>
</p>

<p>
  <strong>Option d:</strong>
  <%= @my_question.option_d %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @my_question.anwser %>
</p>

<p>
  <strong>Question type:</strong>
  <%= @my_question.question_type %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @my_question.created_by %>
</p>

<p>
  <strong>Difficulty level:</strong>
  <%= @my_question.difficulty_level %>
</p>

<%= link_to 'Edit', edit_my_question_path(@my_question) %> |
<%= link_to 'Back', my_questions_path %>