erecruitment/config/routes.rb
Erecruitment::Application.routes.draw do

  resources :answers

  get "testpaper/test"
  get "candidates/index"
  get "candidates/show_tests"
  get "candidates/show_results"
  get "candidate/index"
  get "organization/index"
  resources :tests

  get 'admin' => 'admin#index'
 
controller :sessions do
 get 'login' => :new
 post 'login' => :create
 delete 'logout' => :destroy
end
  
  resources :users

  get "testpaper/index"

  resources :my_questions

end

erecruitment/app/models/answer.rb
class Answer < ActiveRecord::Base
	attr_accessible :test_id , :user_id , :question_id , :selected_answer, :notificatio_status
end

erecruitment/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  

  


  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
    question_id=params[:question_id]
    @q_id=params[:question_id]
    @test_id=params[:test_id]
    @user_id=params[:user_id]
    @current_question=My_question.find(question_id)
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create

    @answer = Answer.new(:test_id=> session[:test_id], :user_id => session[:user_id], :question_id => session[:question_id], :selected_answer => params[:selected_option])

    #respond_to do |format|
      if @answer.save
        tid=session[:test_id]
        qid=session[:question_id]
        #session[:test_id]=nil
        #session[:question_id]=nil
        redirect_to testpaper_test_url(:test_id => tid , :question_id => qid)
      else
        format.html { render action: 'new' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    #end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:test_id, :user_id, :question_id, :selected_answer)
    end
end

erecruitment/app/helpers/answers_helper.rb
module AnswersHelper
end

erecruitment/app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Question%><br>
    <%= @current_question.question %>
  </div>

  <div class="field">
    <%= radio_button_tag(:selected_option, @current_question.option_a) %>
    <%= label_tag(:option_a_label, @current_question.option_a) %>
  </div>

  <div class="field">
    <%= radio_button_tag(:selected_option, @current_question.option_b) %>
    <%= label_tag(:option_b_label, @current_question.option_b) %>
  </div>

  <div class="field">
    <%= radio_button_tag(:selected_option, @current_question.option_c) %>
    <%= label_tag(:option_c_label, @current_question.option_c) %>
  </div>

  <div class="field">
    <%= radio_button_tag(:selected_option, @current_question.option_d) %>
    <%= label_tag(:option_d_label, @current_question.option_d) %>
  </div>
 
  <div class="actions">
    <%= f.submit "Save & next" %>
  </div>
<% end %>






<%
=begin
%>
<% @temp.each do |my_question| %>


<div class="entry">
   
<h3><%= my_question.question %></h3>
<% qid=my_question.id %>
<h4><%= radio_button_tag(:selected_option, "option_a") %>
<%= label_tag(:option_a_label, my_question.option_a) %> </h4>

<h4><%= radio_button_tag(:selected_option, "option_b") %>
<%= label_tag(:option_b_label, my_question.option_b) %> </h4>

<h4><%= radio_button_tag(:selected_option, "option_c") %>
<%= label_tag(:option_c_label, my_question.option_c) %> </h4>

<h4><%= radio_button_tag(:selected_option, "option_d") %>
<%= label_tag(:option_d_label, my_question.option_d) %> </h4>
</div>

<% end %>

<% next_q =((@temp.total_pages == @temp.current_page) ? '' : 'next') %>

<%= will_paginate @temp, :next_label => next_q %>

<% if((@temp.total_pages == @temp.current_page)) %>
  <div>
    <% Notification.test_complete(@user).deliver %>

    <%= button_to 'Submit test', candidates_index_path, :method => "get" %>
  </div>
<% end %>
<%
=end
%>

erecruitment/app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

erecruitment/app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <thead>
    <tr>
      <th>Test</th>
      <th>User</th>
      <th>Question</th>
      <th>Selected answer</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.test_id %></td>
        <td><%= answer.user_id %></td>
        <td><%= answer.question_id %></td>
        <td><%= answer.selected_answer %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

erecruitment/app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

erecruitment/app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Test:</strong>
  <%= @answer.test_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @answer.user_id %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<p>
  <strong>Selected answer:</strong>
  <%= @answer.selected_answer %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>